const fs = require('fs');

function parseEnv(text) {
  const result = {};
  for (const rawLine of String(text || '').split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const equals = line.indexOf('=');
    if (equals < 1) continue;
    const key = line.slice(0, equals).trim();
    let value = line.slice(equals + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    result[key] = value;
  }
  return result;
}

function loadEnvFile(filename, { override = false } = {}) {
  if (!fs.existsSync(filename)) return {};
  const values = parseEnv(fs.readFileSync(filename, 'utf8'));
  for (const [key, value] of Object.entries(values)) {
    if (override || process.env[key] == null) process.env[key] = value;
  }
  return values;
}

function safeEnvValue(value) {
  const text = String(value ?? '');
  if (/[\r\n\0]/.test(text)) throw new Error('Environment values cannot contain newlines or null bytes');
  return text;
}

function renderEnv(values) {
  const sections = [
    ['Application', ['NODE_ENV', 'PORT', 'JWT_SECRET', 'ALLOW_REGISTRATION', 'BUDGET_DB_PATH', 'SERVICE_LOG_DB_PATH']],
    ['Email', ['SMTP_HOST', 'SMTP_PORT', 'SMTP_SECURE', 'SMTP_USER', 'SMTP_PASS', 'SMTP_FROM']],
    ['Encryption', ['SIMPLEFIN_ENCRYPTION_KEY', 'CUSTOMER_DATA_MASTER_KEY']],
    ['Optional IP geolocation', ['MAXMIND_CITY_DB_PATH']],
  ];
  const lines = ['# Generated by npm run setup. Keep this file private and out of Git.', ''];
  for (const [heading, keys] of sections) {
    lines.push(`# ${heading}`);
    for (const key of keys) lines.push(`${key}=${safeEnvValue(values[key])}`);
    lines.push('');
  }
  return `${lines.join('\n').trim()}\n`;
}

module.exports = { loadEnvFile, parseEnv, renderEnv, safeEnvValue };
